"use client";
import { FormEvent, useState } from "react";
import { Database, RotateCcw, Save, Settings2, ShieldCheck } from "lucide-react";
import { useWorkspace } from "@/components/workspace-provider";
import { Modal, SectionHeading } from "@/components/ui";
export function SettingsView() { const { state, updateSettings, reset } = useWorkspace(); const [name, setName] = useState(state.name); const [email, setEmail] = useState(state.email); const [workspace, setWorkspace] = useState(state.workspace); const [notice, setNotice] = useState(""); const [confirmReset, setConfirmReset] = useState(false);
  const submit = (e: FormEvent) => { e.preventDefault(); if (!name.trim() || !workspace.trim()) { setNotice("Enter a name and workspace name before saving."); return; } updateSettings({ name: name.trim(), email: email.trim(), workspace: workspace.trim() }); setNotice("Demo preferences saved in this browser."); };
  const doReset = () => { reset(); setName("Alex Morgan"); setEmail("alex@example.test"); setWorkspace("Northstar Studio"); setConfirmReset(false); setNotice("Sample workspace restored. Local changes were removed."); };
  return <><SectionHeading eyebrow="YOUR WORKSPACE" title="Settings" description="Personalize the local demo and understand what this concept stores."/>{notice && <div className="success-box" role="status">{notice}</div>}<div className="settings-grid"><section className="surface settings-card"><div className="card-header"><div><span className="eyebrow">LOCAL PROFILE</span><h2>Workspace details</h2></div><Settings2 size={19}/></div><form className="form-stack" onSubmit={submit}><label>Your name<input required value={name} onChange={e => setName(e.target.value)}/></label><label>Email address<input required type="email" value={email} onChange={e => setEmail(e.target.value)}/></label><label>Workspace name<input required value={workspace} onChange={e => setWorkspace(e.target.value)}/></label><button type="submit" className="button button-dark"><Save size={16}/> Save changes</button></form></section><div className="settings-side"><section className="surface settings-card"><div className="card-header"><div><span className="eyebrow">PREFERENCES</span><h2>Notifications</h2></div><ShieldCheck size={19}/></div><label className="setting-toggle"><span><strong>Activity updates</strong><small>Visual demo preference only; no alerts are sent.</small></span><input type="checkbox" checked={state.notifications} onChange={e => updateSettings({ notifications: e.target.checked })}/></label></section><section className="surface settings-card"><div className="card-header"><div><span className="eyebrow">DATA & STORAGE</span><h2>Browser storage</h2></div><Database size={19}/></div><p>Documents, conversations, workflow edits, and settings are saved on this device. No files or questions are sent to a server by this concept application.</p><p>TXT and Markdown content is kept as searchable text. PDF and DOCX entries keep metadata only. This is a portfolio demonstration, not a secure document vault.</p><button type="button" className="button button-outline danger-outline" onClick={() => setConfirmReset(true)}><RotateCcw size={16}/> Reset demo data</button></section></div></div><Modal title="Reset local demo" open={confirmReset} onClose={() => setConfirmReset(false)}><div className="modal-form"><p>Restore the fictional sample workspace? This removes documents, collections, conversations, runs, and changes saved by this demo in your browser.</p><div className="modal-actions"><button type="button" className="button button-outline" onClick={() => setConfirmReset(false)}>Keep my changes</button><button type="button" className="button button-dark" onClick={doReset}>Reset demo</button></div></div></Modal></>;
}
