"use client";
import { FormEvent, useState } from "react";
import { Mail, Plus, UsersRound } from "lucide-react";
import { useWorkspace } from "@/components/workspace-provider";
import { Badge, Modal, SectionHeading } from "@/components/ui";
import { Member } from "@/lib/demo";
export function TeamView() { const { state, setMemberRole, inviteMember } = useWorkspace(); const [open, setOpen] = useState(false); const [email, setEmail] = useState(""); const [role, setRole] = useState<Member["role"]>("Viewer"); const [notice, setNotice] = useState("");
  const submit = (e: FormEvent) => { e.preventDefault(); if (state.members.some(m => m.email.toLowerCase() === email.trim().toLowerCase())) { setNotice("That email is already in the sample team."); return; } inviteMember(email.trim(), role); setNotice(`Simulated invitation added for ${email.trim()}. No email was sent.`); setOpen(false); setEmail(""); };
  return <><SectionHeading eyebrow="PEOPLE & ACCESS" title="Team" description="A fictional team to show how shared knowledge could be managed." action={<button className="button button-dark" type="button" onClick={() => { setNotice(""); setOpen(true); }}><Plus size={17}/> Invite teammate</button>}/><div className="team-banner"><UsersRound size={18}/><span>All members and roles are demonstration data. Role changes are visual only and do not enforce access permissions.</span></div>{notice && <div className="success-box" role="status">{notice}</div>}<div className="surface team-surface"><div className="card-header"><div><span className="eyebrow">WORKSPACE MEMBERS</span><h2>{state.members.length} people</h2></div><Badge tone="blue">Fictional team</Badge></div><div className="table-scroll"><table className="data-table"><thead><tr><th scope="col">MEMBER</th><th scope="col">EMAIL</th><th scope="col">ROLE</th><th scope="col">STATUS</th></tr></thead><tbody>{state.members.map(m => <tr key={m.id}><td><div className="member-name"><span className={`avatar avatar-${m.color}`}>{m.initials}</span><strong>{m.name}</strong></div></td><td>{m.email}</td><td><label><span className="visually-hidden">Role for {m.name}</span><select value={m.role} onChange={e => setMemberRole(m.id, e.target.value as Member["role"])}><option>Admin</option><option>Editor</option><option>Viewer</option></select></label></td><td><Badge tone="teal">Demo member</Badge></td></tr>)}</tbody></table></div></div><Modal title="Simulate an invitation" open={open} onClose={() => setOpen(false)}><form className="form-stack modal-form" onSubmit={submit}>{notice && <p className="form-error" role="alert">{notice}</p>}<p className="muted">This adds a local demo member. It will not send an invitation or grant access.</p><label>Email address<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="teammate@example.com"/></label><label>Role<select value={role} onChange={e => setRole(e.target.value as Member["role"])}><option>Viewer</option><option>Editor</option><option>Admin</option></select></label><div className="modal-actions"><button type="button" className="button button-outline" onClick={() => setOpen(false)}>Cancel</button><button type="submit" className="button button-dark"><Mail size={16}/> Add demo member</button></div></form></Modal></>;
}

