"use client";
import { FileText, Trash2 } from "lucide-react";
import { useWorkspace } from "@/components/workspace-provider";
import { Badge, Modal } from "@/components/ui";
import { formatBytes } from "@/lib/demo";
export function DocumentDetail({ id, onClose }: { id: string | null; onClose: () => void }) {
  const { state, renameDocument, assignDocument, deleteDocument } = useWorkspace(); const doc = state.documents.find(d => d.id === id);
  return <Modal title="Document details" open={!!doc} onClose={onClose}>{doc && <div className="document-detail"><div className="detail-icon"><FileText size={24}/></div><div className="detail-heading"><span className="eyebrow">DOCUMENT / {doc.kind}</span><h3>{doc.title}</h3><Badge tone={doc.status === "Ready" ? "teal" : "amber"}>{doc.status}</Badge></div><div className="detail-meta"><div><span>OWNER</span><strong>{doc.owner}</strong></div><div><span>UPDATED</span><strong>{doc.date}</strong></div><div><span>SIZE</span><strong>{formatBytes(doc.size)}</strong></div></div><div className="detail-fields"><label>Document name<input key={doc.id} defaultValue={doc.title} onBlur={e => { if (e.target.value.trim()) renameDocument(doc.id, e.target.value); }} onKeyDown={e => { if (e.key === "Enter") e.currentTarget.blur(); }}/></label><label>Collection<select value={doc.collectionId} onChange={e => assignDocument(doc.id, e.target.value)}>{state.collections.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="detail-text"><div><span className="eyebrow">SOURCE CONTENT</span><span>{doc.text ? "Plain text preview" : "Metadata only"}</span></div>{doc.text ? <p>{doc.text}</p> : <p>PDF and DOCX files are stored as metadata only in this demo. Their contents are not parsed, searched, or sent anywhere.</p>}</div><div className="detail-actions"><button type="button" className="button button-outline danger-outline" onClick={() => { if (window.confirm(`Remove ${doc.title} from this local demo?`)) { deleteDocument(doc.id); onClose(); } }}><Trash2 size={16}/> Delete document</button><button type="button" className="button button-dark" onClick={onClose}>Done</button></div></div>}</Modal>;
}
