"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, Copy, LockKeyhole } from "lucide-react";
import { Brand } from "@/components/brand";
import { initialState, STORAGE_KEY, validSavedState } from "@/lib/demo";

function saveDemoProfile(name: string, email: string, workspace: string) {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    const parsed: unknown = raw ? JSON.parse(raw) : null;
    const state = validSavedState(parsed) ? parsed : initialState();
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...state, name, email, workspace }));
    return true;
  } catch { return false; }
}
export function AuthPage({ mode }: { mode: "login" | "signup" }) {
  const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [workspace, setWorkspace] = useState(""); const [error, setError] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); if (!email.includes("@")) { setError("Enter a valid email address."); return; } if (mode === "signup" && (!name.trim() || !workspace.trim())) { setError("Add your name and workspace name."); return; } const saved = saveDemoProfile(mode === "signup" ? name.trim() : "Demo visitor", email.trim(), mode === "signup" ? workspace.trim() : "Northstar Studio"); if (!saved) setError("Browser storage is unavailable. You can still explore the demo, but changes may not persist."); else router.push("/app"); };
  return <main className="auth-layout"><div className="auth-panel"><Brand/><div className="auth-form-wrap"><span className="eyebrow">CONCEPT PROJECT / LOCAL DEMO</span><h1>{mode === "signup" ? "Make room for clearer work." : "Welcome back to clarity."}</h1><p>{mode === "signup" ? "Create a local demo identity and explore the fictional NEXA workspace." : "Enter an email to personalize this browser demo. There is no real account or password."}</p><form onSubmit={submit} className="form-stack">{mode === "signup" && <label>Full name<input required value={name} onChange={e => setName(e.target.value)} placeholder="Alex Morgan" autoComplete="name"/></label>}<label>Email address<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/></label>{mode === "signup" && <label>Workspace name<input required value={workspace} onChange={e => setWorkspace(e.target.value)} placeholder="Your studio"/></label>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-dark" type="submit">{mode === "signup" ? "Create local workspace" : "Enter demo workspace"} <ArrowRight size={17}/></button></form><div className="auth-divider">or</div><Link className="button button-outline full" href="/app">Explore the sample workspace <ArrowRight size={17}/></Link><p className="auth-switch">{mode === "signup" ? <>Already explored? <Link href="/login">Log in to demo</Link></> : <>New to NEXA? <Link href="/signup">Create a demo workspace</Link></>}</p></div><span className="auth-foot">All data stays in this browser · <Link href="/">Back to website</Link></span></div><div className="auth-visual"><span className="eyebrow">THE WORKSPACE, EXPLAINED</span><div className="auth-visual-center"><div className="auth-visual-icon"><LockKeyhole size={27}/></div><h2>Your team&apos;s context,<br/>finally connected.</h2><p>Organize source material, explore prepared answers, and simulate the workflow from document to action.</p><div><span><Check size={15}/> Local state</span><span><Check size={15}/> Source references</span><span><Check size={15}/> No API key</span></div></div><span className="concept-label">NEXA / Concept Project</span></div></main>;
}
export function DemoRequestPage() { const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [goal, setGoal] = useState(""); const [summary, setSummary] = useState(""); const [copied, setCopied] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!name.trim() || !email.includes("@") || !goal.trim()) return; setCopied(false); setSummary(`NEXA concept demo request\nName: ${name.trim()}\nEmail: ${email.trim()}\nGoal: ${goal.trim()}\n\nThis request was prepared locally and has not been sent.`); };
  return <main className="request-page"><div className="container"><Brand/><div className="request-card"><span className="eyebrow">CONCEPT PROJECT / DEMO REQUEST</span><h1>Tell us what you&apos;d explore.</h1><p>This form prepares a copyable demo brief locally. It does not send a message or book a meeting.</p><form onSubmit={submit} className="form-stack"><label>Your name<input required value={name} onChange={e => setName(e.target.value)} placeholder="Alex Morgan"/></label><label>Email address<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com"/></label><label>What would you want to see?<textarea required minLength={10} value={goal} onChange={e => setGoal(e.target.value)} rows={4} placeholder="For example, how a team traces decisions to source documents"/></label><button className="button button-dark" type="submit">Prepare request <ArrowRight size={17}/></button></form>{summary && <div className="request-summary" aria-live="polite"><strong>Prepared locally — not sent</strong><pre>{summary}</pre><button type="button" className="button button-outline" onClick={async () => { try { await navigator.clipboard.writeText(summary); setCopied(true); } catch { setCopied(false); } }}><Copy size={16}/>{copied ? "Copied" : "Copy request"}</button></div>}</div><Link href="/" className="inline-link"><ArrowLeft size={13} strokeWidth={1.8} aria-hidden="true"/>Back to website</Link></div></main>; }

