"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { Badge } from "@/components/ui";
export function PricingContent() { const [annual, setAnnual] = useState(false); const plans = [
  { name: "Free", monthly: 0, annual: 0, description: "Explore the basics with a small workspace.", items: ["1 workspace", "Up to 50 documents", "Basic search", "Community support"] },
  { name: "Team", monthly: 24, annual: 19, description: "Bring team knowledge and workflows together.", items: ["Unlimited collections", "Source-linked answers", "Workflow templates", "Usage insights"] },
  { name: "Business", monthly: 59, annual: 49, description: "For growing teams with deeper coordination.", items: ["Advanced permissions", "Expanded usage", "Priority support", "Integration options"] },
]; return <section className="marketing-section pricing-section"><div className="container"><div className="pricing-head"><div><span className="eyebrow">ILLUSTRATIVE PLANS</span><h2>Simple in principle.</h2><p>Concept pricing in USD per workspace, per month. These tiers are for product demonstration.</p></div><div className="segmented" aria-label="Billing interval"><button type="button" className={!annual ? "selected" : ""} onClick={() => setAnnual(false)} aria-pressed={!annual}>Monthly</button><button type="button" className={annual ? "selected" : ""} onClick={() => setAnnual(true)} aria-pressed={annual}>Annual <span>Save ~20%</span></button></div></div><div className="pricing-grid">{plans.map(plan => <div className={`pricing-card ${plan.name === "Team" ? "featured" : ""}`} key={plan.name}><div className="pricing-card-top"><h3>{plan.name}</h3>{plan.name === "Team" && <Badge tone="teal">Popular concept</Badge>}</div><p>{plan.description}</p><div className="price"><strong>${annual ? plan.annual : plan.monthly}</strong><span>/ month<br/>concept rate</span></div><Link href="/app" className={`button ${plan.name === "Team" ? "button-dark" : "button-outline"}`}>Explore demo <ArrowRight size={16}/></Link><div className="pricing-includes">INCLUDES</div><ul>{plan.items.map(item => <li key={item}><Check size={16}/>{item}</li>)}</ul></div>)}</div><p className="pricing-disclaimer">Concept content only. Features, limits, and prices are illustrative; no purchase or subscription is available.</p></div></section>; }
